version: '3'
volumes:
  server_node_modules:
  client_node_modules:
services:
    mongo:
        container_name: $PROJECT_NAME-mongo
        image: mongo:latest
        restart: always
        env_file: .env
        environment:
            MONGO_INITDB_ROOT_USERNAME: $MONGO_USER
            MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASS
            MONGO_INITDB_DATABASE: $MONGO_DBNAME
        volumes:
            - ./docker/mongo/db:/data/db
            - ./docker/mongo/config:/data/configdb
        networks:
            internal-network:
            external-network:
                aliases:
                    - $PROJECT_NAME-mongo
    ipfs:
        container_name: $PROJECT_NAME-ipfs
        image: ipfs/go-ipfs:latest
        restart: always
        env_file: .env
    geth:
        container_name: $PROJECT_NAME-geth
        image: kunstmaan/ethereum-geth:latest
        restart: always
        env_file: .env
        networks:
            internal-network:
            external-network:
                aliases:
                    - $PROJECT_NAME-geth
        depends_on:
            - ipfs
    server:
        container_name: $PROJECT_NAME-server
        build: ./server
        restart: always
        env_file: .env
        depends_on:
            - mongo
            - geth
        volumes:
            - ./server/:/project
        command: "npm run dev"
        networks:
            internal-network:
            external-network:
                aliases:
                    - $PROJECT_NAME-server
        environment:
            NODE_ENV: $APP_ENV
            PORT: $APP_PORT
            COMMUNITY_API_SECRET: $SERVER_SECRET
            COMMUNITY_IPFS_HOST:  ${PROJECT_NAME}-ipfs
            COMMUNITY_IPFS_PORT: $IPFS_PORT
            COMMUNITY_IPFS_PROTOCOL: $IPFS_PROTO
            COMMUNITY_IPFS_TIMEOUT: $IPFS_READ_TIMEOUT
            COMMUNITY_MONGO_URI: "mongo://${PROJECT_NAME}-mongo/${MONGO_DBNAME}"
            COMMUNITY_MONGO_USER: $MONGO_USER
            COMMUNITY_MONGO_PASS: $MONGO_PASS
            COMMUNITY_MONGO_AUTH_SOURCE: $MONGO_AUTH_SOURCE
            COMMUNITY_MANDRILL_API_KEY: $MANDRILL_API
            COMMUNITY_MANDRILL_SEND_TO: $MANDRILL_SEND_TO
            COMMUNITY_MAILCHIMP_API_BASE: $MAILCHIMP_API_BASE
            COMMUNITY_MAILCHIMP_LIST: $MAILCHIMP_LIST_NAME
            COMMUNITY_AMAZON_BUCKET_API: $AMAZON_BUCKET_API
    client:
        container_name: $PROJECT_NAME-client
        build: ./client
        restart: always
        env_file: .env
        depends_on:
            - server
        volumes:
            - ./client/:/project
        command: "npm start"
        networks:
            internal-network:
            external-network:
                aliases:
                    - $PROJECT_NAME-client
        environment:
            NODE_ENV: $APP_ENV
            PORT: $APP_PORT
            COMMUNITY_COLU_HOST: $COLU_HOST

networks:
  internal-network:
  external-network:
    external:
      name: $PROJECT_NAME
